# Generated by Django 2.2.5 on 2021-02-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=32)),
                ('movie', models.ManyToManyField(to='movies.Movies')),
            ],
            options={
                'db_table': 'classification',
            },
        ),
    ]
