# Generated by Django 2.2.5 on 2021-02-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classification',
            table=None,
        ),
    ]
