# Generated by Django 2.2.5 on 2021-02-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210224_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table=None,
        ),
    ]
