# Generated by Django 2.2.5 on 2021-02-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210225_0128'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
